# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\PyCharmProjects\PyQt_withHub\CyberMed\src\PyQT-version\UIs\PreSavedMoves.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fist_compress_btn = QtWidgets.QPushButton(self.centralwidget)
        self.fist_compress_btn.setGeometry(QtCore.QRect(100, 60, 71, 31))
        self.fist_compress_btn.setObjectName("fist_compress_btn")
        self.fist_label = QtWidgets.QLabel(self.centralwidget)
        self.fist_label.setGeometry(QtCore.QRect(40, 60, 51, 31))
        self.fist_label.setObjectName("fist_label")
        self.fist_release_btn = QtWidgets.QPushButton(self.centralwidget)
        self.fist_release_btn.setGeometry(QtCore.QRect(190, 60, 75, 31))
        self.fist_release_btn.setObjectName("fist_release_btn")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget.setGeometry(QtCore.QRect(460, 30, 800, 600))
        self.openGLWidget.setObjectName("openGLWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fist_compress_btn.setText(_translate("MainWindow", "Compress"))
        self.fist_label.setText(_translate("MainWindow", "Fist"))
        self.fist_release_btn.setText(_translate("MainWindow", "Release"))
